name: Deploy the example Svelte app that demonstrates a usage of the markdown server.

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-svelte-app:
    runs-on: ubuntu-latest
    name: Node 16
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build the Svelte app
        env:
          MD_SERVER_URL: ${{ secrets.MD_SERVER_URL }}
        run: |
          cd usage/client
          npm ci
          npm run build
      - name: Archive production build of the Svelte app.
        uses: actions/upload-pages-artifact@v1
        with:
          path: usage/client/dist/
  deploy-pages:
    needs: build-svelte-app
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
